project:
  type: book
  output-dir: .

book:
  title: Doctoral Thesis Title
  date: "2025"
  author:
    name: Your Name
    url:
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd

  site-url: https://www.ugent.be/
  repo-url: https://github.com/your-username/your-thesis
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor:
    name: Prof. Dr. Supervisor Name
    url:
  degree-name: Doctor of Philosophy (PhD)
  university: Ghent University
  department: Your Department
  group: Your Research Group
  faculty: Your Faculty
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
    attribution: Dave Barry
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  logo: images/logo.png
  logo-height: "3cm"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
# UGent blue: RGB(30, 100, 200)
format:
  quarto-thesis-pdf:
    urlcolor: ugentblue
    linkcolor: ugentblue
    citecolor: ugentblue
    toclinkcolor: black
    toc-depth: 2
    mainfont: "Arial"
    fontsize: 12pt

